// Data for the Linux Firewall & ACL Sandbox (iptables, ufw, firewalld)

export const IPTABLES_CHAINS = [
  {
    chain: 'INPUT',
    purpose: 'Packets destined for local sockets (programs running directly on this host).',
    secPlusNote: 'Most host hardening rules are applied to the INPUT chain to protect local daemons (SSH, Web, DB).',
    kenyanMetaphor: 'Visitors arriving at your estate front gate who want to visit your house directly.'
  },
  {
    chain: 'OUTPUT',
    purpose: 'Packets generated by local processes on this machine leaving for the network.',
    secPlusNote: 'Used for egress filtering to prevent malware reverse shells or data exfiltration.',
    kenyanMetaphor: 'You driving out through your estate gate to head into town.'
  },
  {
    chain: 'FORWARD',
    purpose: 'Packets routed through this machine to another destination (used if Linux acts as a router/gateway).',
    secPlusNote: 'In standard host security, FORWARD default policy is always set to DROP.',
    kenyanMetaphor: 'Random motorists trying to use your estate private driveway as a bypass shortcut to get between two highways.'
  }
];

export const IPTABLES_TARGETS = [
  {
    target: 'ACCEPT',
    badge: 'ALLOW 🟢',
    description: 'Permits the packet to pass through the chain to its destination socket.',
    portScanEffect: 'Port State: OPEN (Server answers SYN with SYN-ACK)',
    kenyanMetaphor: 'Karibu ndani! The gate guard opens the barrier and directs you to a parking slot.'
  },
  {
    target: 'DROP',
    badge: 'STEALTH SILENCE ⬛',
    description: 'Silently discards the packet into a black hole with ZERO response sent back.',
    portScanEffect: 'Port State: FILTERED (Scanner timer expires; attacker does not know if machine exists)',
    kenyanMetaphor: 'Total blackout silence! The guard sits quietly behind the gate without making a sound or turning on lights. The visitor knocks in the dark until they give up, never knowing if anyone lives there.'
  },
  {
    target: 'REJECT',
    badge: 'ACTIVE BOUNCE 🔴',
    description: 'Blocks packet and sends an active ICMP Port Unreachable or TCP RST back to sender.',
    portScanEffect: 'Port State: CLOSED (Scanner immediately knows a firewall actively rejected the knock)',
    kenyanMetaphor: 'The guard steps to the gate, shouts "Toka hapa mara moja!" and slams the iron padlock shut (RST). The visitor immediately knows someone is guarding inside.'
  }
];

export const DEFAULT_IPTABLES_RULES = [
  {
    id: 'ip-1',
    chain: 'INPUT',
    proto: 'tcp',
    src: '10.10.10.0/24',
    dport: '22',
    target: 'ACCEPT',
    cmd: 'iptables -A INPUT -p tcp -s 10.10.10.0/24 --dport 22 -j ACCEPT',
    explanation: 'Allow administrative SSH strictly from the trusted management subnet.'
  },
  {
    id: 'ip-2',
    chain: 'INPUT',
    proto: 'tcp',
    src: '0.0.0.0/0',
    dport: '443',
    target: 'ACCEPT',
    cmd: 'iptables -A INPUT -p tcp -s 0.0.0.0/0 --dport 443 -j ACCEPT',
    explanation: 'Allow all public internet visitors to browse the HTTPS web application.'
  },
  {
    id: 'ip-3',
    chain: 'INPUT',
    proto: 'tcp',
    src: '0.0.0.0/0',
    dport: '23',
    target: 'DROP',
    cmd: 'iptables -A INPUT -p tcp -s 0.0.0.0/0 --dport 23 -j DROP',
    explanation: 'Silently drop all unencrypted Telnet connection attempts.'
  }
];

export const UFW_DEFAULT_CONFIG = {
  status: 'active',
  incoming: 'deny',
  outgoing: 'allow',
  rules: [
    {
      num: 1,
      action: 'ALLOW',
      direction: 'IN',
      from: '10.10.10.0/24',
      portProto: '22/tcp',
      cmd: 'sudo ufw allow from 10.10.10.0/24 to any port 22 proto tcp',
      explanation: 'Limit SSH management to the admin LAN.'
    },
    {
      num: 2,
      action: 'ALLOW',
      direction: 'IN',
      from: 'Anywhere',
      portProto: '443/tcp',
      cmd: 'sudo ufw allow 443/tcp',
      explanation: 'Allow public HTTPS connections from all internet clients.'
    },
    {
      num: 3,
      action: 'DENY',
      direction: 'IN',
      from: 'Anywhere',
      portProto: '23/tcp',
      cmd: 'sudo ufw deny 23/tcp',
      explanation: 'Explicitly reject cleartext Telnet requests.'
    }
  ]
};

export const FIREWALLD_ZONES = [
  {
    name: 'public',
    trustLevel: 'Untrusted Public Network',
    desc: 'For use in public areas. You do not trust other computers. Only selected incoming connections are accepted.',
    defaultServices: ['ssh', 'dhcpv6-client'],
    kenyanMetaphor: 'The busy Matatu terminus at OTC / Country Bus: Anyone can walk past your vehicle, you do NOT trust anyone, so only verified doors (SSH) are unlocked.'
  },
  {
    name: 'dmz',
    trustLevel: 'Screened Subnet (DMZ)',
    desc: 'Computers in your demilitarized zone that are publicly accessible with limited access to your internal network.',
    defaultServices: ['ssh', 'https', 'http'],
    kenyanMetaphor: 'The visitor waiting bench outside your main house: Public visitors can sit and wait, but there are zero keys to the inner family rooms.'
  },
  {
    name: 'internal',
    trustLevel: 'Internal Trusted LAN',
    desc: 'For use on internal networks. Other computers on the network are generally trusted. More services are accepted.',
    defaultServices: ['ssh', 'mdns', 'samba-client', 'dhcpv6-client'],
    kenyanMetaphor: 'Inside the gated family compound: Everyone inside is a trusted family member or resident, so file sharing and printing are permitted freely.'
  },
  {
    name: 'trusted',
    trustLevel: 'Full Trust',
    desc: 'All network connections are accepted indiscriminately.',
    defaultServices: ['ALL'],
    kenyanMetaphor: 'Your own private bedroom: 100% full trust, no locks between the bed and closet.'
  }
];

export const LINUX_FIREWALL_PBQ = {
  scenario: {
    title: 'Harden Compromised Ubuntu Server (Web & Admin)',
    host: 'web01.corp.internal (192.168.1.100)',
    vulnerabilityAlert: 'An external scan revealed unencrypted Telnet (23) and MySQL (3306) open to the internet (0.0.0.0/0). SSH (22) is open to the entire world without IP restrictions.',
    objective: 'Select the correct firewall rules to enforce Least Privilege: (1) Default deny incoming, (2) Allow HTTPS 443 to ANY, (3) Restrict SSH 22 strictly to Admin Subnet 10.10.10.0/24, (4) Block Telnet 23.'
  },
  questions: [
    {
      id: 'q_default_policy',
      title: 'Step 1: Set Default Inbound Policy',
      prompt: 'Which command correctly sets the default inbound behavior to drop all traffic not explicitly permitted?',
      options: [
        { id: 'a', cmd: 'sudo ufw default allow incoming', isCorrect: false, feedback: 'Dangerous! This allows all incoming traffic by default.' },
        { id: 'b', cmd: 'sudo ufw default deny incoming', isCorrect: true, feedback: 'Correct! This establishes the essential Implicit Deny baseline.' },
        { id: 'c', cmd: 'sudo iptables -P INPUT ACCEPT', isCorrect: false, feedback: 'Incorrect! This sets the default policy to open/accept.' }
      ]
    },
    {
      id: 'q_ssh_restrict',
      title: 'Step 2: Restrict SSH to Admin Subnet',
      prompt: 'Which command allows SSH (Port 22 TCP) only from the authorized administrative subnet (10.10.10.0/24)?',
      options: [
        { id: 'a', cmd: 'sudo ufw allow 22', isCorrect: false, feedback: 'This opens SSH to ANY IP address on the internet!' },
        { id: 'b', cmd: 'sudo ufw allow from 10.10.10.0/24 to any port 22 proto tcp', isCorrect: true, feedback: 'Correct! Restricts destination port 22 TCP specifically to the 10.10.10.0/24 network.' },
        { id: 'c', cmd: 'sudo ufw deny from 10.10.10.0/24 to port 22', isCorrect: false, feedback: 'This would lock out the administrators!' }
      ]
    },
    {
      id: 'q_web_allow',
      title: 'Step 3: Allow Public Web Traffic',
      prompt: 'Which command opens secure web browsing (HTTPS Port 443) to all public users?',
      options: [
        { id: 'a', cmd: 'sudo ufw allow 443/tcp', isCorrect: true, feedback: 'Correct! Permitted for all incoming TCP 443 web sessions.' },
        { id: 'b', cmd: 'sudo ufw allow 80/udp', isCorrect: false, feedback: 'Incorrect! Standard HTTPS is TCP Port 443, not UDP 80.' },
        { id: 'c', cmd: 'sudo iptables -A INPUT -p udp --dport 443 -j ACCEPT', isCorrect: false, feedback: 'Standard TLS web browsing uses TCP.' }
      ]
    },
    {
      id: 'q_firewalld_trap',
      title: 'Step 4: CompTIA Exam Trap (Firewalld Persistence)',
      prompt: 'If configuring firewalld on RHEL, which command ensures that opening port 443 survives a system reboot?',
      options: [
        { id: 'a', cmd: 'firewall-cmd --zone=public --add-service=https', isCorrect: false, feedback: 'Exam Trap! Without --permanent, this rule will disappear upon reboot or reload!' },
        { id: 'b', cmd: 'firewall-cmd --zone=public --add-service=https --permanent && firewall-cmd --reload', isCorrect: true, feedback: 'Correct! --permanent saves to disk, and --reload updates active kernel memory without dropping sessions.' },
        { id: 'c', cmd: 'iptables-save > /dev/null', isCorrect: false, feedback: 'Dumping to /dev/null discards the rules!' }
      ]
    }
  ]
};
